version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      STATD_HOST: graphite
      STATD_PORT: 8125
  graphite:
    image: graphiteapp/graphite-statsd:1.1.8-1
